services:
 catalogdb:
  image: postgres:17-alpine


 catelog.api:
   image: ${DOCKER_REGISTRY-}catelogapi
   build:
    context: .
    dockerfile: Services/Catalog/Catelog.API/Dockerfile

volumes:
 postgres_catalog:

